spring.application.name=aggregationservice
server.servlet.context-path=/aggregationservice/api

spring.profiles.active=db
server.port=8080
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

candle.generator.enabled=true
candle.generator.rate-ms=200
candle.aggregation.grace-period-sec=5
candle.aggregation.queue-capacity=10000
logging.level.com.candle=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/aggregation
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false